spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8086
              predicates:
                - Path=/auth/v1/**
            - id: url-service
              uri: http://url-service:8083
              predicates:
                - Path=/api/v1/urls/**,/url/public/v1/**
              filters:
                - AuthenticationFilter
            - id: analytics-service
              uri: http://analytics-service:8085
              predicates:
                - Path=/api/v1/analytics/**
              filters:
                - AuthenticationFilter
server:
  port: 8087