spring:
  application:
    name: url-service

  datasource:
    url: jdbc:postgresql://localhost:5451/url
    username: postgres
    password: postgres

    jpa:
      hibernate:
        ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6380
      username: redis
      password: redis

  cache:
    type: redis


server:
  port: 8082
