spring:
  application:
    name: url-service

  datasource:
    url: jdbc:postgresql://localhost:5451/url
    username: postgres
    password: postgres

    jpa:
      hibernate:
        ddl-auto: none

Spring:
  data:
    redis:
      url: redis://localhost:6380


  cache:
    type: redis


server:
  port: 8082
